// <auto-generated />
using System;
using ABJAD.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABJAD.Server.Migrations
{
    [DbContext(typeof(AbjadContext))]
    [Migration("20201205213650_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ABJAD.Server.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("ABJAD.Server.Models.NewFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("NewFeature");
                });

            modelBuilder.Entity("ABJAD.Server.Models.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Number")
                        .HasColumnType("real");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("ABJAD.Server.Models.VersionArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("VersionId");

                    b.ToTable("VersionArticle");
                });

            modelBuilder.Entity("ABJAD.Server.Models.NewFeature", b =>
                {
                    b.HasOne("ABJAD.Server.Models.Version", "Version")
                        .WithMany("NewFeatures")
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("ABJAD.Server.Models.VersionArticle", b =>
                {
                    b.HasOne("ABJAD.Server.Models.Article", "Article")
                        .WithMany("Versions")
                        .HasForeignKey("ArticleId");

                    b.HasOne("ABJAD.Server.Models.Version", "Version")
                        .WithMany("Articles")
                        .HasForeignKey("VersionId");

                    b.Navigation("Article");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("ABJAD.Server.Models.Article", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ABJAD.Server.Models.Version", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("NewFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
